<?php

namespace Dili\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkTimeRepository extends EntityRepository
{
}
